// Stage registry: which labels exist and which variables each stage provides.
// Keys and variable names are a contract with the stage flows and saved templates.

export const LABEL_STAGE_KEYS = {
  INBOUND: 'inbound',
  CUTTER_ISSUE: 'cutter_issue',
  CUTTER_ISSUE_SMALL: 'cutter_issue_small',
  CUTTER_RECEIVE: 'cutter_receive',
  HOLO_ISSUE: 'holo_issue',
  HOLO_RECEIVE: 'holo_receive',
  CONING_ISSUE: 'coning_issue',
  CONING_RECEIVE: 'coning_receive',
  CONING_RECEIVE_SMALL: 'coning_receive_small',
};

export const STAGE_GROUPS = [
  { key: 'inbound', label: 'Inbound', stages: [LABEL_STAGE_KEYS.INBOUND] },
  { key: 'cutter', label: 'Cutter', stages: [LABEL_STAGE_KEYS.CUTTER_ISSUE, LABEL_STAGE_KEYS.CUTTER_ISSUE_SMALL, LABEL_STAGE_KEYS.CUTTER_RECEIVE] },
  { key: 'holo', label: 'Holo', stages: [LABEL_STAGE_KEYS.HOLO_ISSUE, LABEL_STAGE_KEYS.HOLO_RECEIVE] },
  { key: 'coning', label: 'Coning', stages: [LABEL_STAGE_KEYS.CONING_ISSUE, LABEL_STAGE_KEYS.CONING_RECEIVE, LABEL_STAGE_KEYS.CONING_RECEIVE_SMALL] },
];

export const STAGE_LABELS = {
  [LABEL_STAGE_KEYS.INBOUND]: 'Inbound lot',
  [LABEL_STAGE_KEYS.CUTTER_ISSUE]: 'Issue to cutter',
  [LABEL_STAGE_KEYS.CUTTER_ISSUE_SMALL]: 'Issue to cutter · small',
  [LABEL_STAGE_KEYS.CUTTER_RECEIVE]: 'Receive from cutter',
  [LABEL_STAGE_KEYS.HOLO_ISSUE]: 'Issue to holo',
  [LABEL_STAGE_KEYS.HOLO_RECEIVE]: 'Receive from holo',
  [LABEL_STAGE_KEYS.CONING_ISSUE]: 'Issue to coning',
  [LABEL_STAGE_KEYS.CONING_RECEIVE]: 'Receive from coning',
  [LABEL_STAGE_KEYS.CONING_RECEIVE_SMALL]: 'Receive from coning · small',
};

export const STAGE_VARIABLES = {
  [LABEL_STAGE_KEYS.INBOUND]: [
    { key: 'lotNo', label: 'Lot No' },
    { key: 'itemName', label: 'Item Name' },
    { key: 'firmName', label: 'Firm Name' },
    { key: 'supplierName', label: 'Supplier Name' },
    { key: 'pieceId', label: 'Piece ID' },
    { key: 'seq', label: 'Sequence' },
    { key: 'weight', label: 'Weight' },
    { key: 'date', label: 'Date' },
    { key: 'barcode', label: 'Barcode' },
  ],
  [LABEL_STAGE_KEYS.CUTTER_ISSUE]: [
    { key: 'lotNo', label: 'Lot No' },
    { key: 'itemName', label: 'Item Name' },
    { key: 'pieceId', label: 'Piece ID' },
    { key: 'seq', label: 'Sequence' },
    { key: 'inboundDate', label: 'Lot Inbound Date' },
    { key: 'cut', label: 'Cut' },
    { key: 'count', label: 'Pieces Count' },
    { key: 'totalWeight', label: 'Total Weight' },
    { key: 'machineName', label: 'Machine' },
    { key: 'operatorName', label: 'Operator' },
    { key: 'date', label: 'Date' },
    { key: 'barcode', label: 'Issue Barcode' },
  ],
  [LABEL_STAGE_KEYS.CUTTER_ISSUE_SMALL]: [
    { key: 'lotNo', label: 'Lot No' },
    { key: 'itemName', label: 'Item Name' },
    { key: 'pieceId', label: 'Piece ID' },
    { key: 'seq', label: 'Sequence' },
    { key: 'inboundDate', label: 'Lot Inbound Date' },
    { key: 'cut', label: 'Cut' },
    { key: 'count', label: 'Pieces Count' },
    { key: 'totalWeight', label: 'Total Weight' },
    { key: 'machineName', label: 'Machine' },
    { key: 'operatorName', label: 'Operator' },
    { key: 'date', label: 'Date' },
    { key: 'barcode', label: 'Issue Barcode' },
  ],
  [LABEL_STAGE_KEYS.CUTTER_RECEIVE]: [
    { key: 'lotNo', label: 'Lot No' },
    { key: 'itemName', label: 'Item Name' },
    { key: 'pieceId', label: 'Piece ID' },
    { key: 'seq', label: 'Sequence' },
    { key: 'netWeight', label: 'Net Weight' },
    { key: 'grossWeight', label: 'Gross Weight' },
    { key: 'tareWeight', label: 'Tare Weight' },
    { key: 'bobbinQty', label: 'Bobbin Qty' },
    { key: 'bobbinName', label: 'Bobbin' },
    { key: 'boxName', label: 'Box' },
    { key: 'cutName', label: 'Cut (Old)' },
    { key: 'cut', label: 'Cut' },
    { key: 'machineName', label: 'Machine' },
    { key: 'helperName', label: 'Helper' },
    { key: 'operatorName', label: 'Operator' },
    { key: 'shift', label: 'Shift' },
    { key: 'date', label: 'Date' },
    { key: 'barcode', label: 'Receive Barcode' },
  ],
  [LABEL_STAGE_KEYS.HOLO_ISSUE]: [
    { key: 'lotNo', label: 'Lot No' },
    { key: 'itemName', label: 'Item Name' },
    { key: 'totalRolls', label: 'Total Rolls' },
    { key: 'totalWeight', label: 'Total Weight' },
    { key: 'netWeight', label: 'Net Weight' },
    { key: 'bobbinQty', label: 'Bobbin Qty' },
    { key: 'bobbinType', label: 'Bobbin Type' },
    { key: 'cut', label: 'Cut' },
    { key: 'yarnKg', label: 'Yarn Kg' },
    { key: 'twistName', label: 'Twist (Old)' },
    { key: 'twist', label: 'Twist' },
    { key: 'yarnName', label: 'Yarn' },
    { key: 'machineName', label: 'Machine' },
    { key: 'operatorName', label: 'Operator' },
    { key: 'shift', label: 'Shift' },
    { key: 'date', label: 'Date' },
    { key: 'barcode', label: 'Issue Barcode' },
  ],
  [LABEL_STAGE_KEYS.HOLO_RECEIVE]: [
    { key: 'lotNo', label: 'Lot No' },
    { key: 'itemName', label: 'Item Name' },
    { key: 'rollCount', label: 'Roll Count' },
    { key: 'grossWeight', label: 'Gross Weight' },
    { key: 'tareWeight', label: 'Tare Weight' },
    { key: 'netWeight', label: 'Net Weight' },
    { key: 'rollType', label: 'Roll Type' },
    { key: 'boxName', label: 'Box' },
    { key: 'cut', label: 'Cut' },
    { key: 'yarnName', label: 'Yarn' },
    { key: 'twist', label: 'Twist' },
    { key: 'machineName', label: 'Machine' },
    { key: 'operatorName', label: 'Operator' },
    { key: 'shift', label: 'Shift' },
    { key: 'date', label: 'Date' },
    { key: 'barcode', label: 'Receive Barcode' },
  ],
  [LABEL_STAGE_KEYS.CONING_ISSUE]: [
    { key: 'lotNo', label: 'Lot No' },
    { key: 'itemName', label: 'Item Name' },
    { key: 'cut', label: 'Cut' },
    { key: 'yarnName', label: 'Yarn' },
    { key: 'twist', label: 'Twist' },
    { key: 'rollType', label: 'Roll Type' },
    { key: 'coneType', label: 'Cone Type' },
    { key: 'wrapperName', label: 'Wrapper' },
    { key: 'totalRolls', label: 'Total Rolls' },
    { key: 'rollCount', label: 'Roll Count' },
    { key: 'totalWeight', label: 'Total Weight' },
    { key: 'grossWeight', label: 'Gross Weight' },
    { key: 'tareWeight', label: 'Tare Weight' },
    { key: 'netWeight', label: 'Net Weight' },
    { key: 'expectedCones', label: 'Expected Cones' },
    { key: 'perConeTargetG', label: 'Target g/cone' },
    { key: 'machineName', label: 'Machine' },
    { key: 'operatorName', label: 'Operator' },
    { key: 'date', label: 'Date' },
    { key: 'barcode', label: 'Issue Barcode' },
    { key: 'shift', label: 'Shift' },
  ],
  [LABEL_STAGE_KEYS.CONING_RECEIVE]: [
    { key: 'barcodeNumber', label: 'Barcode Number (text only)' },
    { key: 'lotNo', label: 'Lot No' },
    { key: 'itemName', label: 'Item Name' },
    { key: 'cut', label: 'Cut' },
    { key: 'yarnName', label: 'Yarn' },
    { key: 'twist', label: 'Twist' },
    { key: 'rollType', label: 'Roll Type' },
    { key: 'coneType', label: 'Cone Type' },
    { key: 'wrapperName', label: 'Wrapper' },
    { key: 'issueBarcode', label: 'Issue Barcode' },
    { key: 'barcode', label: 'Receive Barcode' },
    { key: 'rollCount', label: 'Roll Count' },
    { key: 'coneCount', label: 'Cone Count' },
    { key: 'grossWeight', label: 'Gross Weight' },
    { key: 'tareWeight', label: 'Tare Weight' },
    { key: 'netWeight', label: 'Net Weight' },
    { key: 'shift', label: 'Shift' },
    { key: 'boxName', label: 'Box' },
    { key: 'operatorName', label: 'Operator' },
    { key: 'machineName', label: 'Machine' },
    { key: 'date', label: 'Date' },
  ],
  [LABEL_STAGE_KEYS.CONING_RECEIVE_SMALL]: [
    { key: 'barcodeNumber', label: 'Barcode Number (text only)' },
    { key: 'lotNo', label: 'Lot No' },
    { key: 'itemName', label: 'Item Name' },
    { key: 'cut', label: 'Cut' },
    { key: 'yarnName', label: 'Yarn' },
    { key: 'twist', label: 'Twist' },
    { key: 'rollType', label: 'Roll Type' },
    { key: 'coneType', label: 'Cone Type' },
    { key: 'wrapperName', label: 'Wrapper' },
    { key: 'issueBarcode', label: 'Issue Barcode' },
    { key: 'barcode', label: 'Receive Barcode' },
    { key: 'rollCount', label: 'Roll Count' },
    { key: 'coneCount', label: 'Cone Count' },
    { key: 'grossWeight', label: 'Gross Weight' },
    { key: 'tareWeight', label: 'Tare Weight' },
    { key: 'netWeight', label: 'Net Weight' },
    { key: 'shift', label: 'Shift' },
    { key: 'boxName', label: 'Box' },
    { key: 'operatorName', label: 'Operator' },
    { key: 'date', label: 'Date' },
  ],
};

export const getStageVariables = (stage) => STAGE_VARIABLES[stage] || [];
export const getStageLabel = (stage) => STAGE_LABELS[stage] || stage;
