-- Add createdAt/updatedAt timestamps across workflow + master tables.
-- This migration is additive-only (no drops) and includes backfills for existing rows.

-- ===== Masters / Config =====

ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3);
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
UPDATE "Item" SET "createdAt" = CURRENT_TIMESTAMP WHERE "createdAt" IS NULL;
UPDATE "Item" SET "updatedAt" = COALESCE("updatedAt", "createdAt") WHERE "updatedAt" IS NULL;
ALTER TABLE "Item" ALTER COLUMN "createdAt" SET NOT NULL;
ALTER TABLE "Item" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Item" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "Item" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Yarn" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3);
ALTER TABLE "Yarn" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
UPDATE "Yarn" SET "createdAt" = CURRENT_TIMESTAMP WHERE "createdAt" IS NULL;
UPDATE "Yarn" SET "updatedAt" = COALESCE("updatedAt", "createdAt") WHERE "updatedAt" IS NULL;
ALTER TABLE "Yarn" ALTER COLUMN "createdAt" SET NOT NULL;
ALTER TABLE "Yarn" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Yarn" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "Yarn" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Cut" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3);
ALTER TABLE "Cut" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
UPDATE "Cut" SET "createdAt" = CURRENT_TIMESTAMP WHERE "createdAt" IS NULL;
UPDATE "Cut" SET "updatedAt" = COALESCE("updatedAt", "createdAt") WHERE "updatedAt" IS NULL;
ALTER TABLE "Cut" ALTER COLUMN "createdAt" SET NOT NULL;
ALTER TABLE "Cut" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Cut" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "Cut" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Twist" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3);
ALTER TABLE "Twist" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
UPDATE "Twist" SET "createdAt" = CURRENT_TIMESTAMP WHERE "createdAt" IS NULL;
UPDATE "Twist" SET "updatedAt" = COALESCE("updatedAt", "createdAt") WHERE "updatedAt" IS NULL;
ALTER TABLE "Twist" ALTER COLUMN "createdAt" SET NOT NULL;
ALTER TABLE "Twist" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Twist" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "Twist" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Firm" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3);
ALTER TABLE "Firm" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
UPDATE "Firm" SET "createdAt" = CURRENT_TIMESTAMP WHERE "createdAt" IS NULL;
UPDATE "Firm" SET "updatedAt" = COALESCE("updatedAt", "createdAt") WHERE "updatedAt" IS NULL;
ALTER TABLE "Firm" ALTER COLUMN "createdAt" SET NOT NULL;
ALTER TABLE "Firm" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Firm" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "Firm" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3);
ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
UPDATE "Supplier" SET "createdAt" = CURRENT_TIMESTAMP WHERE "createdAt" IS NULL;
UPDATE "Supplier" SET "updatedAt" = COALESCE("updatedAt", "createdAt") WHERE "updatedAt" IS NULL;
ALTER TABLE "Supplier" ALTER COLUMN "createdAt" SET NOT NULL;
ALTER TABLE "Supplier" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Supplier" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "Supplier" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Machine" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3);
ALTER TABLE "Machine" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
UPDATE "Machine" SET "createdAt" = CURRENT_TIMESTAMP WHERE "createdAt" IS NULL;
UPDATE "Machine" SET "updatedAt" = COALESCE("updatedAt", "createdAt") WHERE "updatedAt" IS NULL;
ALTER TABLE "Machine" ALTER COLUMN "createdAt" SET NOT NULL;
ALTER TABLE "Machine" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Machine" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "Machine" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Operator" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3);
ALTER TABLE "Operator" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
UPDATE "Operator" SET "createdAt" = CURRENT_TIMESTAMP WHERE "createdAt" IS NULL;
UPDATE "Operator" SET "updatedAt" = COALESCE("updatedAt", "createdAt") WHERE "updatedAt" IS NULL;
ALTER TABLE "Operator" ALTER COLUMN "createdAt" SET NOT NULL;
ALTER TABLE "Operator" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Operator" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "Operator" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Bobbin" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3);
ALTER TABLE "Bobbin" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
UPDATE "Bobbin" SET "createdAt" = CURRENT_TIMESTAMP WHERE "createdAt" IS NULL;
UPDATE "Bobbin" SET "updatedAt" = COALESCE("updatedAt", "createdAt") WHERE "updatedAt" IS NULL;
ALTER TABLE "Bobbin" ALTER COLUMN "createdAt" SET NOT NULL;
ALTER TABLE "Bobbin" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Bobbin" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "Bobbin" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Box" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3);
ALTER TABLE "Box" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
UPDATE "Box" SET "createdAt" = CURRENT_TIMESTAMP WHERE "createdAt" IS NULL;
UPDATE "Box" SET "updatedAt" = COALESCE("updatedAt", "createdAt") WHERE "updatedAt" IS NULL;
ALTER TABLE "Box" ALTER COLUMN "createdAt" SET NOT NULL;
ALTER TABLE "Box" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Box" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "Box" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "RollType" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
UPDATE "RollType" SET "updatedAt" = "createdAt" WHERE "updatedAt" IS NULL;
ALTER TABLE "RollType" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "RollType" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "ConeType" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
UPDATE "ConeType" SET "updatedAt" = "createdAt" WHERE "updatedAt" IS NULL;
ALTER TABLE "ConeType" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "ConeType" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Wrapper" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
UPDATE "Wrapper" SET "updatedAt" = "createdAt" WHERE "updatedAt" IS NULL;
ALTER TABLE "Wrapper" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "Wrapper" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "WhatsappTemplate" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3);
ALTER TABLE "WhatsappTemplate" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
UPDATE "WhatsappTemplate" SET "createdAt" = CURRENT_TIMESTAMP WHERE "createdAt" IS NULL;
UPDATE "WhatsappTemplate" SET "updatedAt" = COALESCE("updatedAt", "createdAt") WHERE "updatedAt" IS NULL;
ALTER TABLE "WhatsappTemplate" ALTER COLUMN "createdAt" SET NOT NULL;
ALTER TABLE "WhatsappTemplate" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "WhatsappTemplate" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "WhatsappTemplate" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3);
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
UPDATE "Settings" SET "createdAt" = CURRENT_TIMESTAMP WHERE "createdAt" IS NULL;
UPDATE "Settings" SET "updatedAt" = COALESCE("updatedAt", "createdAt") WHERE "updatedAt" IS NULL;
ALTER TABLE "Settings" ALTER COLUMN "createdAt" SET NOT NULL;
ALTER TABLE "Settings" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Settings" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "Settings" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Sequence" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3);
ALTER TABLE "Sequence" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
UPDATE "Sequence" SET "createdAt" = CURRENT_TIMESTAMP WHERE "createdAt" IS NULL;
UPDATE "Sequence" SET "updatedAt" = COALESCE("updatedAt", "createdAt") WHERE "updatedAt" IS NULL;
ALTER TABLE "Sequence" ALTER COLUMN "createdAt" SET NOT NULL;
ALTER TABLE "Sequence" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Sequence" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "Sequence" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "HoloIssueSequence" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3);
ALTER TABLE "HoloIssueSequence" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
UPDATE "HoloIssueSequence" SET "createdAt" = CURRENT_TIMESTAMP WHERE "createdAt" IS NULL;
UPDATE "HoloIssueSequence" SET "updatedAt" = COALESCE("updatedAt", "createdAt") WHERE "updatedAt" IS NULL;
ALTER TABLE "HoloIssueSequence" ALTER COLUMN "createdAt" SET NOT NULL;
ALTER TABLE "HoloIssueSequence" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "HoloIssueSequence" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "HoloIssueSequence" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "ConingIssueSequence" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3);
ALTER TABLE "ConingIssueSequence" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
UPDATE "ConingIssueSequence" SET "createdAt" = CURRENT_TIMESTAMP WHERE "createdAt" IS NULL;
UPDATE "ConingIssueSequence" SET "updatedAt" = COALESCE("updatedAt", "createdAt") WHERE "updatedAt" IS NULL;
ALTER TABLE "ConingIssueSequence" ALTER COLUMN "createdAt" SET NOT NULL;
ALTER TABLE "ConingIssueSequence" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "ConingIssueSequence" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "ConingIssueSequence" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- ===== Workflow / Transactions =====

ALTER TABLE "Lot" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
UPDATE "Lot" SET "updatedAt" = "createdAt" WHERE "updatedAt" IS NULL;
ALTER TABLE "Lot" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "Lot" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "InboundItem" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
UPDATE "InboundItem" SET "updatedAt" = "createdAt" WHERE "updatedAt" IS NULL;
ALTER TABLE "InboundItem" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "InboundItem" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "IssueToCutterMachine" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3);
ALTER TABLE "IssueToCutterMachine" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
UPDATE "IssueToCutterMachine" SET "createdAt" = CURRENT_TIMESTAMP WHERE "createdAt" IS NULL;
UPDATE "IssueToCutterMachine" SET "updatedAt" = COALESCE("updatedAt", "createdAt") WHERE "updatedAt" IS NULL;
ALTER TABLE "IssueToCutterMachine" ALTER COLUMN "createdAt" SET NOT NULL;
ALTER TABLE "IssueToCutterMachine" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "IssueToCutterMachine" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "IssueToCutterMachine" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "ReceiveFromCutterMachineUpload" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3);
ALTER TABLE "ReceiveFromCutterMachineUpload" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
UPDATE "ReceiveFromCutterMachineUpload" SET "createdAt" = "uploadedAt" WHERE "createdAt" IS NULL;
UPDATE "ReceiveFromCutterMachineUpload" SET "updatedAt" = "uploadedAt" WHERE "updatedAt" IS NULL;
ALTER TABLE "ReceiveFromCutterMachineUpload" ALTER COLUMN "createdAt" SET NOT NULL;
ALTER TABLE "ReceiveFromCutterMachineUpload" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "ReceiveFromCutterMachineUpload" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "ReceiveFromCutterMachineUpload" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "ReceiveFromCutterMachineRow" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
UPDATE "ReceiveFromCutterMachineRow" SET "updatedAt" = "createdAt" WHERE "updatedAt" IS NULL;
ALTER TABLE "ReceiveFromCutterMachineRow" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "ReceiveFromCutterMachineRow" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "ReceiveFromCutterMachinePieceTotal" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3);
UPDATE "ReceiveFromCutterMachinePieceTotal"
SET "createdAt" = COALESCE("updatedAt", CURRENT_TIMESTAMP)
WHERE "createdAt" IS NULL;
ALTER TABLE "ReceiveFromCutterMachinePieceTotal" ALTER COLUMN "createdAt" SET NOT NULL;
ALTER TABLE "ReceiveFromCutterMachinePieceTotal" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "IssueToHoloMachine" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
UPDATE "IssueToHoloMachine" SET "updatedAt" = "createdAt" WHERE "updatedAt" IS NULL;
ALTER TABLE "IssueToHoloMachine" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "IssueToHoloMachine" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "ReceiveFromHoloMachineRow" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
UPDATE "ReceiveFromHoloMachineRow" SET "updatedAt" = "createdAt" WHERE "updatedAt" IS NULL;
ALTER TABLE "ReceiveFromHoloMachineRow" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "ReceiveFromHoloMachineRow" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "ReceiveFromHoloMachinePieceTotal" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3);
UPDATE "ReceiveFromHoloMachinePieceTotal"
SET "createdAt" = COALESCE("updatedAt", CURRENT_TIMESTAMP)
WHERE "createdAt" IS NULL;
ALTER TABLE "ReceiveFromHoloMachinePieceTotal" ALTER COLUMN "createdAt" SET NOT NULL;
ALTER TABLE "ReceiveFromHoloMachinePieceTotal" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "IssueToConingMachine" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
UPDATE "IssueToConingMachine" SET "updatedAt" = "createdAt" WHERE "updatedAt" IS NULL;
ALTER TABLE "IssueToConingMachine" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "IssueToConingMachine" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "ReceiveFromConingMachineRow" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
UPDATE "ReceiveFromConingMachineRow" SET "updatedAt" = "createdAt" WHERE "updatedAt" IS NULL;
ALTER TABLE "ReceiveFromConingMachineRow" ALTER COLUMN "updatedAt" SET NOT NULL;
ALTER TABLE "ReceiveFromConingMachineRow" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "ReceiveFromConingMachinePieceTotal" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3);
UPDATE "ReceiveFromConingMachinePieceTotal"
SET "createdAt" = COALESCE("updatedAt", CURRENT_TIMESTAMP)
WHERE "createdAt" IS NULL;
ALTER TABLE "ReceiveFromConingMachinePieceTotal" ALTER COLUMN "createdAt" SET NOT NULL;
ALTER TABLE "ReceiveFromConingMachinePieceTotal" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

