export const PACKING_EVENT_TYPES = Object.freeze({
  BATCH_CONFIRMED: 'BATCH_CONFIRMED',
  BATCH_STARTED: 'BATCH_STARTED',
  BATCH_TARGET_AMENDED: 'BATCH_TARGET_AMENDED',
  BATCH_COMPLETED: 'BATCH_COMPLETED',
  BATCH_SHORT_CLOSED: 'BATCH_SHORT_CLOSED',
  BATCH_VOIDED: 'BATCH_VOIDED',
  SOURCE_RESERVED: 'SOURCE_RESERVED',
  SOURCE_CONSUMED: 'SOURCE_CONSUMED',
  SOURCE_RELEASED: 'SOURCE_RELEASED',
  UNIT_SEALED: 'UNIT_SEALED',
  UNIT_LABEL_PENDING: 'UNIT_LABEL_PENDING',
  UNIT_LABEL_REPRINTED: 'UNIT_LABEL_REPRINTED',
  UNIT_BARCODE_REPLACED: 'UNIT_BARCODE_REPLACED',
  UNIT_QUALITY_RELEASED: 'UNIT_QUALITY_RELEASED',
  UNIT_RESERVED: 'UNIT_RESERVED',
  UNIT_RESERVATION_RELEASED: 'UNIT_RESERVATION_RELEASED',
  UNIT_RESERVATION_REASSIGNED: 'UNIT_RESERVATION_REASSIGNED',
  UNIT_SPLIT: 'UNIT_SPLIT',
  UNIT_RETURNED: 'UNIT_RETURNED',
  UNIT_RETURN_INSPECTED: 'UNIT_RETURN_INSPECTED',
  UNIT_DAMAGED: 'UNIT_DAMAGED',
  UNIT_WRITTEN_OFF: 'UNIT_WRITTEN_OFF',
  UNIT_REPACKED: 'UNIT_REPACKED',
  ADMINISTRATIVE_AMENDMENT: 'ADMINISTRATIVE_AMENDMENT',
  EVENT_REVERSED: 'EVENT_REVERSED',
});

export const BATCH_STATUSES = Object.freeze({
  DRAFT: 'DRAFT',
  CONFIRMED: 'CONFIRMED',
  IN_PROGRESS: 'IN_PROGRESS',
  PARTIALLY_COMPLETED: 'PARTIALLY_COMPLETED',
  COMPLETED: 'COMPLETED',
  SHORT_CLOSED: 'SHORT_CLOSED',
  VOIDED: 'VOIDED',
});

export const UNIT_STATUSES = Object.freeze({
  IN_PROGRESS: 'IN_PROGRESS',
  LABEL_PENDING: 'LABEL_PENDING',
  QUALITY_HOLD: 'QUALITY_HOLD',
  AVAILABLE: 'AVAILABLE',
  RESERVED: 'RESERVED',
  DISPATCHED: 'DISPATCHED',
  RETURNED_PENDING_INSPECTION: 'RETURNED_PENDING_INSPECTION',
  DAMAGED: 'DAMAGED',
  REPACKED: 'REPACKED',
  SPLIT_CONSUMED: 'SPLIT_CONSUMED',
  OPENED: 'OPENED',
  VOIDED: 'VOIDED',
});

export const ACTIVE_BATCH_STATUSES = ['CONFIRMED', 'IN_PROGRESS', 'PARTIALLY_COMPLETED'];

export const RECIPE_STATUSES = Object.freeze({
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  RETIRED: 'RETIRED',
});

export const PACKAGE_KINDS = ['PACKET', 'BOX', 'BORI', 'PARCEL'];
export const DELIVERY_MODES = ['UNSPECIFIED', 'LOCAL', 'PARCEL'];
export const BATCH_KINDS = ['INITIAL', 'REPACKING', 'OPENING'];
export const SOURCE_TYPES = ['CONING_RECEIVE', 'PACKED_UNIT'];

export const BATCH_TRANSITIONS = Object.freeze({
  DRAFT: ['CONFIRMED', 'VOIDED'],
  CONFIRMED: ['IN_PROGRESS', 'VOIDED'],
  IN_PROGRESS: ['PARTIALLY_COMPLETED', 'VOIDED'],
  PARTIALLY_COMPLETED: ['COMPLETED', 'SHORT_CLOSED'],
  COMPLETED: [],
  SHORT_CLOSED: [],
  VOIDED: [],
});

export const UNIT_TRANSITIONS = Object.freeze({
  IN_PROGRESS: ['LABEL_PENDING', 'QUALITY_HOLD', 'AVAILABLE', 'RESERVED'],
  LABEL_PENDING: ['QUALITY_HOLD', 'AVAILABLE', 'RESERVED'],
  QUALITY_HOLD: ['AVAILABLE', 'RESERVED'],
  AVAILABLE: ['RESERVED', 'DISPATCHED', 'DAMAGED', 'REPACKED', 'SPLIT_CONSUMED', 'OPENED'],
  RESERVED: ['AVAILABLE', 'DISPATCHED', 'DAMAGED', 'REPACKED', 'SPLIT_CONSUMED', 'OPENED'],
  DISPATCHED: ['RETURNED_PENDING_INSPECTION'],
  RETURNED_PENDING_INSPECTION: ['AVAILABLE', 'RESERVED', 'DAMAGED', 'REPACKED'],
  DAMAGED: ['REPACKED'],
  REPACKED: [],
  SPLIT_CONSUMED: [],
  OPENED: [],
  VOIDED: [],
});
