export const glintexOwnerDomainContract = {
  version: 1,
  agentId: 'glintex-owner',
  authority: {
    ownerOnly: true,
    channel: 'telegram-direct',
    shell: false,
    filesystem: false,
    browser: false,
    deployment: false,
    payments: false,
    outboundMessaging: false,
    selfModification: false,
    specialistDelegation: false,
  },
  reads: {
    health: 'Dedicated agent API and database health.',
    reference: 'Live GLINTEX master identifiers and controlled names.',
    issues: { process: ['cutter', 'holo', 'coning'], maximumRows: 100 },
    receives: { process: ['cutter', 'holo', 'coning'], maximumRows: 100 },
    on_machine: { process: ['cutter', 'holo', 'coning'], maximumRows: 100 },
    stock: { process: ['holo', 'coning'], maximumRows: 100 },
    production: {
      process: ['all', 'cutter', 'holo', 'coning'],
      maximumDateRangeDays: 93,
      rule: 'Summarizes non-deleted receive rows using stored net-weight precedence.',
    },
    contractor_settlements: { statuses: ['draft', 'paid'], maximumRows: 100 },
    finance_outstanding: {
      source: 'Tally report API',
      side: ['debtor', 'creditor'],
      maximumRows: 100,
    },
    finance_runs: { source: 'Tally report API', maximumRows: 100 },
    owner_tasks: { statuses: ['OPEN', 'IN_PROGRESS', 'BLOCKED', 'DONE', 'CANCELLED'] },
    learning_candidates: { statuses: ['PROPOSED', 'APPROVED', 'REJECTED', 'APPLIED'] },
    operation_history: 'Redacted operation-ledger history; confirmation hashes and raw credentials are never returned.',
    system_status: 'Agent API, database, application backend, migration, runtime, and deployed-SHA status.',
  },
  actions: {
    owner_task_create: {
      action: 'owner_task.create',
      areas: ['FINANCE', 'INVENTORY', 'TECHNOLOGY', 'APPLICATION', 'OPERATIONS', 'GENERAL'],
      priorities: ['LOW', 'MEDIUM', 'HIGH', 'URGENT'],
    },
    owner_task_update: {
      action: 'owner_task.update',
      requires: ['exact taskId', 'fresh expectedVersion'],
    },
    owner_task_complete: {
      action: 'owner_task.complete',
      requires: ['exact taskId', 'fresh expectedVersion'],
    },
    owner_task_cancel: {
      action: 'owner_task.cancel',
      requires: ['exact taskId', 'fresh expectedVersion'],
    },
    learning_candidate_propose: {
      action: 'learning_candidate.propose',
      categories: ['OWNER_PREFERENCE', 'DOMAIN_RULE', 'WORKFLOW_GAP', 'PROCESS_IMPROVEMENT'],
      effect: 'Creates a review candidate only; never changes active memory, policy, tools, model, or routing.',
    },
  },
  mutationProtocol: {
    prepare: 'Validate, duplicate-check, store preview, and return an expiring one-time code.',
    confirm: 'The authenticated owner must send exactly CONFIRM GLINTEX GLX-XXXXXXXXXX in a new current message.',
    execute: 'Atomically claim and execute one prepared operation through the durable ledger.',
    verify: 'Read back the stored entity and operation audit before claiming completion.',
    idempotency: 'Every preparation requires a stable unique idempotency key. Reuse with different data is rejected.',
    optimisticConcurrency: 'Updates require the latest exact version and fail closed on drift.',
  },
  dataRules: {
    currentFacts: 'Fresh tool reads override memory and historical chat context.',
    identifiers: 'Use exact live IDs; never guess or select an ambiguous fuzzy match.',
    cutTracing: 'For downstream stages, prefer Coning Issue receivedRowRefs to Holo Receive rows to Holo Issue; use the coning issue cut only when trace data is unavailable.',
    totals: 'Use application-computed or adapter-documented totals and disclose active filters and date ranges.',
    tally: 'Treat Tally snapshots as accounting evidence, disclose freshness, and do not infer a payment from amount similarity.',
  },
} as const;
